[platformio]
default_envs = native

[env]
test_framework = unity
build_flags =
  -std=c++11
  -Wall
  -Wextra
  -Wpedantic
  -Wconversion
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,style,performance,portability
  cppcheck: --std=c++11
  cppcheck: --inline-suppr

[env:native]
platform = native
build_unflags =
  -std=gnu++11

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_unflags =
  -std=gnu++11
